//
// Created by sanek on 28/01/2024.
//

#ifndef INC_2D_GAME_ENGINE_SRC_COMPONENTS_CAMERAFOLLOWCOMPONENT_H_
#define INC_2D_GAME_ENGINE_SRC_COMPONENTS_CAMERAFOLLOWCOMPONENT_H_
struct CameraFollowComponent{
    CameraFollowComponent() = default;
};
#endif //INC_2D_GAME_ENGINE_SRC_COMPONENTS_CAMERAFOLLOWCOMPONENT_H_
